RedditViewer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('picviewer.urls', namespace="picviewer")),
)

picviewer/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from picviewer import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^r/(?P<subreddit>[A-z0-9\-_+]+)/(?P<order>hot|new|rising|controversial|top|)$', views.subredditSort, name='subredditSort'),
    url(r'^(?P<order>hot|new|rising|controversial|top|)$', views.sort, name='sort'),
    url(r'^r/(?P<subreddit>[A-z0-9\-_+]+)/search$', views.subredditSearch, name='subredditSearch'),
    url(r'^search$', views.default, name='search'),
    url(r'^r/(?P<subreddit>[A-z0-9\-_+]+)$', views.subreddit, name='subreddit'),   
    url(r'^u/(?P<user>[A-z0-9\-_+]+)/(?P<order>hot|new|controversial|top|)$', views.userSort, name='userSort'),
    url(r'^u/(?P<user>[A-z0-9\-_+]+)$', views.user, name='user'),
    url(r'^$', views.default, name='default'),
)

picviewer/models.py
from django.db import models

class User(models.Model):
    uid = models.CharField(max_length=36, primary_key=True)
    created_date = models.DateTimeField()
    last_visited_date = models.DateTimeField()
    allow_nsfw = models.BooleanField(default=False)
    show_details = models.BooleanField(default=False)
    show_all_links = models.BooleanField(default=False)
    user_agent = models.CharField(max_length=150)
    
    def __unicode__(self):
        return self.uid

picviewer/views.py
from django.shortcuts import render
from picviewer.models import User
import datetime
import json
import urllib2
import uuid

def subredditSort(request, subreddit, order):
    return mainView(request, subreddit, order, "");
    
def sort(request, order):
    return mainView(request, "", order, "")

def subredditSearch(request, subreddit):
    return mainView(request, subreddit, "", "")

def subreddit(request, subreddit):
    return mainView(request, subreddit, "", "")

def userSort(request, user, order):
    return mainView(request, "", order, user);

def user(request, user):
    return mainView(request, "", "", user);
        
def default(request):
    return mainView(request, "", "", "")



def mainView(request, subreddit, order, user): 
    context = {}
    context['columns'] = [i for i in range(4)]
    context['subreddits'] = ['adviceanimals', 'aww', 'earthporn', 'funny', 'gaming', 'gifs', 'pics', 'reactiongifs', 'wallpapers', 'wtf']
    context['subreddit'] = subreddit
    context['orders'] = ['hot', 'new', 'rising', 'controversial', 'top']
    context['order'] = order
    context['timeFrames'] = [['day', 'today'], ['hour', 'this hour'], ['week', 'this week'], ['month', 'this month'], ['year', 'this year'], ['all', 'all time']]
    if "t" in request.GET:
        context['timeFrame'] = request.GET["t"]
        context['searchTime'] = request.GET["t"]
    else:
        context['timeFrame'] = "day"
        context['searchTime'] = "all"
    
    context['searchOrders'] = ['relevance', 'hot', 'new', 'top']
    
    if "sort" in request.GET:
        context['searchOrder'] = request.GET["sort"]
    else:
        context['searchOrder'] = "relevance"
        
    if "q" in request.GET:
        context['query'] = request.GET["q"]
    else:
        context['query'] = ""
    
    # retrieve subreddit information    
    if(subreddit == ""):
        context['image'] = "http://b.thumbs.redditmedia.com/harEHsUUZVajabtC.png"
        context['link'] = "http://www.reddit.com";
        context['name'] = ""
        context['subredditDescription'] = ""
    else:
        try:
            h1 = urllib2.urlopen("http://www.reddit.com/r/" + subreddit + "/about.json", timeout=5)
            jsonObj = json.loads(h1.read())
            context['image'] = jsonObj["data"]["header_img"]
            context['link'] = "http://www.reddit.com/r/" + subreddit
            context['name'] = jsonObj["data"]["display_name"]
            context['subredditDescription'] = jsonObj["data"]["public_description"]
        except Exception:
            context['image'] = "http://b.thumbs.redditmedia.com/harEHsUUZVajabtC.png"
            context['link'] = "http://www.reddit.com"
            context['name'] = ""
            context['subredditDescription'] = ""
    
    context['userOrders'] = ['hot', 'new', 'controversial', 'top']
    context['user'] = user
    
    if request.COOKIES.has_key('riv'):
        # returning user, retrieve his/her settings
        try:
            user = User.objects.get(uid=request.COOKIES[ 'riv' ])
        except:
            user = User(uid=request.COOKIES[ 'riv' ], created_date=datetime.datetime.now())
        user.last_visited_date = datetime.datetime.now()
        if "save_settings" in request.POST:
            # user just clicked on save settings button, save the settings
            # to the database
            user.allow_nsfw = "allow_nsfw" in request.POST
            user.show_details = "show_details" in request.POST
            user.show_all_links = "show_all_links" in request.POST
        user.save()
        context["allowNSFW"] = user.allow_nsfw
        context["showDetails"] = user.show_details
        context["showAllLinks"] = user.show_all_links

    else:
        # use default settings
        context["allowNSFW"] = False
        context["showDetails"] = False
        context["showAllLinks"] = False
       
    response = render(request, 'picviewer/index.html', context)
    
    
    # set the cookies for first time users
    if not request.COOKIES.has_key('riv'):
        if "HTTP_USER_AGENT" in request.META:
            user_agent=request.META["HTTP_USER_AGENT"]
        else:
            user_agent=""
        
        # don't set cookies for search bots
        if "Googlebot" not in user_agent:
            uid = uuid.uuid4()
            response.set_cookie(key='riv', value=uid, max_age=31536000)
            user = User(uid=uid, created_date=datetime.datetime.now(), last_visited_date=datetime.datetime.now(),user_agent=user_agent)
            user.save()
        
    return  response

picviewer/templates/picviewer/index.html
<!DOCTYPE html>

{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] ||
                function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o), m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-47444408-1', 'redditviewer.com');
            ga('send', 'pageview');

		</script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
		<script type="text/javascript" src="{% static 'picviewer/js/main.js' %}"></script>
		<script>
            currentState = new CurrentState("{{subreddit}}", "{{order}}", "{{timeFrame}}", "{{query}}", "{{searchTime}}", "{{searchOrder}}", "{{user}}", "{{allowNSFW}}", "{{showDetails}}", "{{showAllLinks}}");
		</script>
		<link type="text/css" rel="stylesheet" href="{% static 'picviewer/css/styles.css' %}" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

		{% if user != "" %}
		<title>u/{{user}} | Reddit Picture Viewer</title>
		{% elif name != "" %}
		<title>r/{{name}} | Reddit Picture Viewer</title>
		{% else %}
		<title>Reddit Picture Viewer</title>
		{% endif %}

		<meta name="author" content="David Zou">
		<meta name="description" content="Image viewer for Reddit.
		{% if name != "" %}
		r/{{name}}: {{subredditDescription}}
		{% endif %}">
		<!-- Date: 2014-01-22 -->
	</head>
	<body>
		<nav id='subredditsBar'>
			<input type='text' id='subredditSearcher' onkeydown='gotoSubreddit(this.value,event.keyCode)' placeholder='Goto subreddit'/>
			<span class="separator">|</span>
			<a class='subredditURL' href='{% url "picviewer:default" %}'>FRONT</a>
			<span class="separator">-</span>
			<a class='subredditURL' href='{% url "picviewer:subreddit" "all" %}'>ALL</a>
			<span class="separator">|</span>
			{% for sr in subreddits %}
			<a class='subredditURL' href='{% url "picviewer:subreddit" sr   %}'>{{sr|upper}}</a>
			{% if not forloop.last%}
			<span class="separator">-</span>
			{% endif %}
			{% endfor %}

			<a id="sourceCode" href="https://github.com/f2rf2r/RedditViewer" target="_blank">Source code</a>
		</nav>

		<header id='headerBar'>
			<a class='logoLink' href='{{link}}' target="_blank"><img id='logo' src='{{image}}' alt="logo"></a>
			{% if user != "" %}
			<a class='logoLink' href='http://www.reddit.com/u/{{user}}' target="_blank"><span id='userName'>u/{{user}}</span></a>
			{% else %}
			<a class='logoLink' href='{{link}}' target="_blank"><span id='subredditName'>{{name}}</span></a>
			{% endif %}
			<nav id='sortBar'>
				{% if user != "" %}
				{% for ord in userOrders %}
				<a class='sortURL' id='sort{{ord}}' href='{% url "picviewer:userSort" user ord  %}'><span class='sortOrder'>{{ord}}</span></a>
				{% endfor %}
				{% elif subreddit != "" %}
				{% for ord in orders %}
				<a class='sortURL' id='sort{{ord}}' href='{% url "picviewer:subredditSort" subreddit ord  %}'><span class='sortOrder'>{{ord}}</span></a>
				{% endfor %}
				{% else %}
				{% for ord in orders %}
				<a class='sortURL' id='sort{{ord}}' href='{% url "picviewer:sort" ord  %}'><span class='sortOrder'>{{ord}}</span></a>
				{% endfor %}
				{% endif %}
			</nav>

			{% if order == "top" or order == "controversial" %}
			<select id="timeFrameSelector" onchange=setTimeFrame(this)>
				{% for t in timeFrames %}
				<option class='timeFrameOption'
				{% if t.0 == timeFrame %} selected {% endif %}
				value={{t.0}}>{{t.1}}</option>
				{% endfor %}
			</select>
			{% endif %}
			<div id="rightHeader">

				<div id='searchBar'>
					<input type='text' id='searchBox' onkeydown='checkSearchBox(event.keyCode)' value="{{query}}" placeholder='Search'/>

					<div id="searchOptions">
						<select id="searchSortSelector">
							{% for so in searchOrders %}
							<option class='searchSortOption'
							{% if so == searchOrder %} selected {% endif %}
							value={{so}}>{{so}}</option>
							{% endfor %}
						</select>
						<select id="searchTimeSelector">
							{% for t in timeFrames %}
							<option class='searchTimeOption'
							{% if t.0 == searchTime %} selected {% endif %}
							value={{t.0}}>{{t.1}}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<button id="searchButton" onclick='sendSearchRequest()'>
					Search
				</button>

				<div id="settingsContainer">
					<button id="settingsButton" onclick="toggleSettingsDropdown()">
						Settings
					</button>
					<form name="settingsForm" action="" method="post">
						{% csrf_token %}
						<ul id="settingsDropdown" onmouseleave="toggleSettingsDropdown()">
							<li class="settingsItem">
								<label class="settingsLabel"> Allow NSFW</label>
								<input class="settingsField" type="checkbox" name="allow_nsfw" value="True" {% if allowNSFW %}checked{% endif %}/>
								<div class="clear"></div>
							</li>
							<li class="settingsItem">
								<label class="settingsLabel"> Always show submission details</label>
								<input class="settingsField" type="checkbox" name="show_details" value="True" {% if showDetails %}checked{% endif %}/>
								<div class="clear"></div>
							</li>
							<li class="settingsItem">
								<label class="settingsLabel"> Show non-image links</label>
								<input class="settingsField" type="checkbox" name="show_all_links" value="True" {% if showAllLinks %}checked{% endif %}/>
								<div class="clear"></div>
							</li>
							<li id="saveSettingsContainer">
								<input id="saveSettingsButton" type="submit" name="save_settings" value="Save"/>
							</li>
						</ul>
					</form>
				</div>
			</div>
		</header>

		<section id='gallery'>
			<script>
                for (var x = 0; x < currentState.numCols; x++) {
                    document.write("<ul class='imageList' id='imageList" + x + "'></ul>");
                }
			</script>
		</section>

		<section id="indicator">
			<noscript>
				Please enable javascript to use this site.
			</noscript>
			<div id='endNotification'>
				There are no more links
			</div>
			<button id="loadMoreButton" onclick='sendRequest()'>
				Load more
			</button>
			<img src="{% static 'picviewer/media/loading.gif' %}" id='loadingGif' alt='Loading...'>

		</section>

		<script>
            setup();
		</script>
	</body>

</html>